variables:
  CONJUR_APPLIANCE_URL: "https://conjur.vx"
  CONJUR_ACCOUNT: "cyberark"
  CONJUR_AUTHN_JWT_SERVICE_ID: "gitlab"
  CONJUR_AUTHN_JWT_TOKEN: "${CI_JOB_JWT_V2}"
  CONJUR_CERT_FILE: "central.pem"
Fetch variables from Conjur:
  stage: .pre
  image:
    name: docker.io/cyberark/authn-jwt-gitlab:alpine-1.0.0
  script:
    - echo MYSQLUSER=$(CONJUR_SECRET_ID="db_cicd/username" /authn-jwt-gitlab) >> conjurVariables.env
    - echo MYSQLPASSWORD=$(CONJUR_SECRET_ID="db_cicd/password" /authn-jwt-gitlab) >> conjurVariables.env
  artifacts:
    reports:
      dotenv: conjurVariables.env
Run MySQL using variables from Conjur:
  stage: test
  image:
    name: docker.io/library/mysql:latest
    entrypoint: [""]
  script:
    - mysql --host=mysql.vx --user=$MYSQLUSER --password=$MYSQLPASSWORD -e 'SELECT city.Name as City,country.name as Country,city.District,city.Population FROM world.city,world.country WHERE city.CountryCode = country.Code ORDER BY RAND() LIMIT 0,1;'
