variables:
  AWS_REGION: ap-southeast-1
  CONJUR_APPLIANCE_URL: https://conjur.vx
  CONJUR_ACCOUNT: cyberark
  CONJUR_AUTHN_JWT_SERVICE_ID: gitlab
  CONJUR_AUTHN_JWT_TOKEN: "${CI_JOB_JWT_V2}"
  CONJUR_CERT_FILE: central.pem
Fetch variables from Conjur:
  stage: .pre
  image:
    name: docker.io/cyberark/authn-jwt-gitlab:alpine-1.0.0
  script:
    - echo AWS_ACCESS_KEY_ID=$(CONJUR_SECRET_ID="aws_api/awsakid" /authn-jwt-gitlab) >> conjurVariables.env
    - echo AWS_SECRET_ACCESS_KEY=$(CONJUR_SECRET_ID="aws_api/awssak" /authn-jwt-gitlab) >> conjurVariables.env
  artifacts:
    reports:
      dotenv: conjurVariables.env
Create bucket using Terraform:
  stage: deploy
  image:
    name: docker.io/hashicorp/terraform:latest
    entrypoint: [""]
  before_script:
    - terraform init
  script:
    - terraform apply -auto-approve
